import Footer from "@/app/_components/Footer";
import NavBar from "@/app/_components/NavBar";
import "./_styles/globals.css";
import { auth } from "./_lib/auth";
export const metadata = {
  title: "Hagora Handmade",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang="en">
      <body>
        <NavBar
          name={session?.user?.name || ""}
          image={session?.user?.image || ""}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
